# Generated by Django 4.0.1 on 2022-01-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default='', max_length=50)),
                ('CourseNumber', models.IntegerField()),
                ('InstructorName', models.CharField(blank=True, default='', max_length=50)),
                ('Duration', models.FloatField()),
            ],
        ),
    ]
